const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={token:sessionStorage.getItem('marketai_admin_token')||'',admin:null,page:'dashboard'};
const titles={dashboard:'Visão geral',users:'Clientes',subscriptions:'Assinaturas',payments:'Pagamentos',licenses:'Licenças',devices:'Dispositivos',plans:'Planos',audit:'Auditoria'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dt=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const money=(v,c='BRL')=>{try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency:c}).format(Number(v||0))}catch{return `${c} ${Number(v||0).toFixed(2)}`}};
const pill=(text,type='')=>`<span class="pill ${type}">${esc(text||'—')}</span>`;
function statusPill(s){const t=String(s||'').toLowerCase(); return pill(s,t==='active'||t==='approved'||t==='trialing'?'green':t==='blocked'||t==='failed'||t==='canceled'?'red':t==='past_due'||t==='pending'||t==='suspended'?'yellow':'');}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.add('hidden'),3000)}
function modal(html){$('#modalBody').innerHTML=html;$('#modalBackdrop').classList.remove('hidden')}
function closeModal(){$('#modalBackdrop').classList.add('hidden');$('#modalBody').innerHTML=''}
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const res=await fetch(path,{...opt,headers});let data={};try{data=await res.json()}catch{}if(!res.ok){if(res.status===401||res.status===403){if(path!='/v1/admin/auth/login')logout(false)}throw new Error(data.detail||`HTTP ${res.status}`)}return data}
async function login(email,password){const d=await api('/v1/admin/auth/login',{method:'POST',body:JSON.stringify({email,password})});state.token=d.access_token;state.admin=d.user;sessionStorage.setItem('marketai_admin_token',state.token);showApp()}
function logout(reload=true){state.token='';state.admin=null;sessionStorage.removeItem('marketai_admin_token');$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');if(reload)location.reload()}
async function bootstrap(){if(!state.token)return;try{state.admin=await api('/v1/admin/me');showApp()}catch{logout(false)}}
function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#adminIdentity').textContent=state.admin?.email||'admin';go(state.page)}
async function go(page){state.page=page;$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$$('.page').forEach(p=>p.classList.remove('active-page'));$(`#page-${page}`).classList.add('active-page');$('#pageTitle').textContent=titles[page];await loaders[page]?.();}

const metricCard=(label,value,sub='',accent='')=>`<div class="metric ${accent}"><div class="kicker">${esc(label)}</div><div class="value">${esc(value)}</div><div class="sub">${esc(sub)}</div></div>`;
function bars(el,rows,key='count',label='plan'){const max=Math.max(1,...rows.map(x=>Number(x[key]||0)));el.innerHTML=rows.length?rows.map(x=>`<div class="bar-row"><span>${esc(x[label])}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,Number(x[key]||0)/max*100)}%"></div></div><b>${esc(x[key])}</b></div>`).join(''):'<span class="muted">Sem dados.</span>'}
async function loadDashboard(){const d=await api('/v1/admin/dashboard');const m=d.metrics;const revenue=Object.entries(m.confirmed_revenue_30d||{}).map(([c,v])=>money(v,c)).join(' · ')||'R$ 0,00';$('#metricGrid').innerHTML=[metricCard('Clientes',m.users,`${m.new_users_30d} novos em 30 dias`,'accent'),metricCard('Assinaturas ativas',m.active_subscriptions,`${m.trials} em teste`),metricCard('Receita confirmada — 30d',revenue,'Transações creditadas'),metricCard('Análises no mês',m.analyses_this_month,'Consumo acumulado'),metricCard('Dispositivos ativos',m.active_devices,`${m.blocked_users} contas bloqueadas`)].join('');$('#recentUsers').innerHTML=d.recent_users.map(u=>`<div class="mini-row"><div><strong>${esc(u.full_name||u.email)}</strong><span>${esc(u.email)} · ${esc(u.subscription.plan_code||'sem plano')}</span></div>${statusPill(u.status)}</div>`).join('')||'<span class="muted">Sem clientes.</span>';$('#recentPayments').innerHTML=d.recent_payments.map(p=>`<div class="mini-row"><div><strong>${money(p.amount,p.currency)}</strong><span>${esc(p.provider)} · ${esc(p.plan_code)} · ${dt(p.created_at)}</span></div>${statusPill(p.status)}</div>`).join('')||'<span class="muted">Sem pagamentos.</span>';bars($('#planBars'),d.plans,'count','plan');bars($('#providerBars'),d.subscription_providers,'count','provider');bars($('#paymentBars'),d.payment_providers_30d,'count','provider');$('#lastUpdated').textContent=`Atualizado ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`}

async function loadUsers(){const qs=new URLSearchParams({q:$('#userSearch').value,status:$('#userStatus').value,plan:$('#userPlan').value});const d=await api('/v1/admin/users?'+qs);$('#usersCount').textContent=d.total;$('#usersTable').innerHTML=d.items.map(u=>`<tr><td><strong>${esc(u.full_name||'Sem nome')}</strong><br><span class="muted">${esc(u.email)}</span></td><td>${statusPill(u.status)}</td><td>${pill(u.subscription.plan_code||'—','blue')}</td><td>${esc(u.subscription.provider||'—')}</td><td>${u.entitlement?.remaining??0}/${u.entitlement?.quota??0}</td><td>${u.active_devices}/${u.entitlement?.device_limit??0}</td><td><div class="table-actions"><button class="ghost small" onclick="openUser('${u.id}')">Abrir</button>${u.status==='active'?`<button class="danger" onclick="setUserStatus('${u.id}','blocked')">Bloquear</button>`:`<button class="success" onclick="setUserStatus('${u.id}','active')">Liberar</button>`}</div></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Nenhum cliente encontrado.</td></tr>'}
async function openUser(id){const u=await api(`/v1/admin/users/${id}`);modal(`<h2>${esc(u.full_name||'Cliente')}</h2><p class="muted">${esc(u.email)} · ${esc(u.id)}</p><div class="modal-grid"><div class="panel"><h3>Conta</h3><div class="detail-row"><span>Status</span>${statusPill(u.status)}</div><div class="detail-row"><span>Plano</span><b>${esc(u.subscription.plan_code||'—')}</b></div><div class="detail-row"><span>Gateway</span><b>${esc(u.subscription.provider||'—')}</b></div><div class="detail-row"><span>Vencimento</span><b>${dt(u.subscription.period_end||u.subscription.trial_end)}</b></div></div><div class="panel"><h3>Uso</h3><div class="detail-row"><span>Restante</span><b>${u.entitlement?.remaining??0} / ${u.entitlement?.quota??0}</b></div><div class="detail-row"><span>Dispositivos</span><b>${u.active_devices} / ${u.entitlement?.device_limit??0}</b></div><button class="ghost small" onclick="resetUsage('${u.id}')">Zerar uso do mês</button></div></div><div class="detail-section"><h3>Alterar assinatura</h3><div class="modal-grid"><label>Plano<select id="grantPlan"><option value="essencial">Essencial</option><option value="pro">Pro</option><option value="business">Business</option></select></label><label>Dias adicionais<input id="grantDays" type="number" min="0" value="30"></label></div><button class="primary" onclick="grantPlan('${u.id}')">Aplicar plano manual</button></div><div class="detail-section"><h3>Dispositivos</h3>${u.devices.map(d=>`<div class="mini-row"><div><strong>${esc(d.name)}</strong><span>${esc(d.device_uuid)} · ${dt(d.last_seen)}</span></div><button class="${d.active?'danger':'success'}" onclick="setDevice('${d.id}',${!d.active});openUser('${u.id}')">${d.active?'Desativar':'Ativar'}</button></div>`).join('')||'<span class="muted">Sem dispositivos.</span>'}</div><div class="detail-section"><h3>Pagamentos recentes</h3>${u.payments.slice(0,8).map(p=>`<div class="mini-row"><div><strong>${money(p.amount,p.currency)}</strong><span>${esc(p.provider)} · ${esc(p.plan_code)} · ${dt(p.created_at)}</span></div>${statusPill(p.status)}</div>`).join('')||'<span class="muted">Sem pagamentos.</span>'}</div>`)}
async function setUserStatus(id,status){if(!confirm(`Alterar esta conta para ${status}?`))return;await api(`/v1/admin/users/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});toast('Status atualizado.');loadUsers()}
async function grantPlan(id){const plan_code=$('#grantPlan').value,days=Number($('#grantDays').value||30);await api(`/v1/admin/users/${id}/subscription`,{method:'PATCH',body:JSON.stringify({plan_code,status:'active',days})});toast('Assinatura manual aplicada.');openUser(id)}
async function resetUsage(id){if(!confirm('Zerar o consumo do mês deste cliente?'))return;await api(`/v1/admin/users/${id}/reset-usage`,{method:'POST',body:'{}'});toast('Uso mensal zerado.');openUser(id)}

async function loadSubscriptions(){const d=await api('/v1/admin/subscriptions');$('#subscriptionsTable').innerHTML=d.items.map(s=>`<tr><td><strong>${esc(s.full_name||'')}</strong><br><span class="muted">${esc(s.email)}</span></td><td>${pill(s.plan_code,'blue')}</td><td>${statusPill(s.status)}</td><td>${esc(s.provider)}</td><td>${dt(s.current_period_end||s.trial_end)}</td><td><span class="muted">${esc((s.provider_subscription_id||'—').slice(0,28))}</span></td></tr>`).join('')||'<tr><td colspan="6" class="muted">Sem assinaturas.</td></tr>'}
async function loadPayments(){const q=new URLSearchParams({provider:$('#paymentProvider').value,status:$('#paymentStatus').value});const d=await api('/v1/admin/payments?'+q);$('#paymentsTable').innerHTML=d.items.map(p=>`<tr><td>${dt(p.created_at)}</td><td><strong>${esc(p.full_name||'')}</strong><br><span class="muted">${esc(p.email)}</span></td><td>${esc(p.provider)}</td><td>${esc(p.payment_method)}</td><td>${esc(p.plan_code)}</td><td><strong>${money(p.amount,p.currency)}</strong></td><td>${statusPill(p.status)}</td><td>${p.credited_at?pill('confirmado','green'):pill('não creditado','')}</td></tr>`).join('')||'<tr><td colspan="8" class="muted">Sem transações.</td></tr>'}
async function loadLicenses(){const d=await api('/v1/admin/licenses');$('#licensesTable').innerHTML=d.items.map(l=>`<tr><td><code>•••••${esc(l.code_hint)}</code></td><td>${pill(l.plan_code,'blue')}</td><td>${l.duration_days} dias</td><td>${l.redeemed_count}/${l.max_redemptions}</td><td>${l.active?pill('ativa','green'):pill('inativa','red')}</td><td>${dt(l.created_at)}</td><td><button class="${l.active?'danger':'success'}" onclick="setLicense('${l.id}',${!l.active})">${l.active?'Desativar':'Ativar'}</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Nenhuma licença.</td></tr>'}
function openCreateLicense(){modal(`<h2>Nova licença comercial</h2><p class="muted">A chave completa aparece apenas uma vez após a criação.</p><label>Plano<select id="licPlan"><option value="pro">Pro</option><option value="business">Business</option><option value="essencial">Essencial</option></select></label><div class="modal-grid"><label>Duração (dias)<input id="licDays" type="number" min="1" value="365"></label><label>Máximo de resgates<input id="licMax" type="number" min="1" value="1"></label></div><button class="primary wide" onclick="createLicense()">Gerar licença</button><div id="licenseResult"></div>`)}
async function createLicense(){const d=await api('/v1/admin/licenses/create',{method:'POST',body:JSON.stringify({plan_code:$('#licPlan').value,duration_days:Number($('#licDays').value),max_redemptions:Number($('#licMax').value)})});$('#licenseResult').innerHTML=`<div class="detail-section"><p class="muted">Copie agora. Por segurança, a chave completa não será exibida novamente.</p><div class="codebox">${esc(d.license_key)}</div><button class="ghost wide" style="margin-top:10px" onclick="navigator.clipboard.writeText('${esc(d.license_key)}');toast('Chave copiada.')">Copiar</button></div>`;loadLicenses()}
async function setLicense(id,active){await api(`/v1/admin/licenses/${id}`,{method:'PATCH',body:JSON.stringify({active})});toast('Licença atualizada.');loadLicenses()}

async function loadDevices(){const d=await api('/v1/admin/devices?'+new URLSearchParams({q:$('#deviceSearch').value}));$('#devicesTable').innerHTML=d.items.map(x=>`<tr><td>${esc(x.email)}</td><td><strong>${esc(x.name)}</strong></td><td><span class="muted">${esc(x.device_uuid)}</span></td><td>${x.active?pill('ativo','green'):pill('inativo','red')}</td><td>${dt(x.first_seen)}</td><td>${dt(x.last_seen)}</td><td><button class="${x.active?'danger':'success'}" onclick="setDevice('${x.id}',${!x.active})">${x.active?'Desativar':'Ativar'}</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Sem dispositivos.</td></tr>'}
async function setDevice(id,active){await api(`/v1/admin/devices/${id}`,{method:'PATCH',body:JSON.stringify({active})});toast('Dispositivo atualizado.');if(state.page==='devices')loadDevices()}

async function loadPlans(){const d=await api('/v1/admin/plans');$('#plansGrid').innerHTML=d.items.map(p=>`<article class="plan-card"><div class="panel-head"><h3>${esc(p.name)}</h3>${p.active?pill('ativo','green'):pill('inativo','red')}</div><div class="plan-price">${money(p.price_brl,'BRL')} <small>/ mês</small></div><div class="plan-fields"><label>Análises/mês<input id="quota-${p.code}" type="number" value="${p.analyses_per_month}"></label><label>Dispositivos<input id="devices-${p.code}" type="number" value="${p.device_limit}"></label></div><label>Preço BRL<input id="price-${p.code}" type="number" step="0.01" value="${p.price_brl}"></label><label><input id="active-${p.code}" type="checkbox" ${p.active?'checked':''} style="width:auto;margin-right:8px">Plano disponível</label><button class="primary wide" onclick="savePlan('${p.code}')">Salvar alterações</button></article>`).join('')}
async function savePlan(code){await api(`/v1/admin/plans/${code}`,{method:'PATCH',body:JSON.stringify({price_brl:Number($(`#price-${code}`).value),analyses_per_month:Number($(`#quota-${code}`).value),device_limit:Number($(`#devices-${code}`).value),active:$(`#active-${code}`).checked})});toast('Plano atualizado.');loadPlans()}

async function loadAudit(){const d=await api('/v1/admin/audit?'+new URLSearchParams({q:$('#auditSearch').value}));$('#auditTable').innerHTML=d.items.map(e=>`<tr><td>${dt(e.created_at)}</td><td>${esc(e.email||e.user_id||'sistema')}</td><td>${pill(e.event,e.event.startsWith('admin.')?'blue':'')}</td><td>${esc(e.detail)}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">Sem eventos.</td></tr>'}
const loaders={dashboard:loadDashboard,users:loadUsers,subscriptions:loadSubscriptions,payments:loadPayments,licenses:loadLicenses,devices:loadDevices,plans:loadPlans,audit:loadAudit};

$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').classList.add('hidden');try{await login($('#loginEmail').value,$('#loginPassword').value)}catch(err){$('#loginError').textContent='Não foi possível entrar: '+err.message;$('#loginError').classList.remove('hidden')}});
$('#logoutBtn').onclick=()=>logout();$('#refreshBtn').onclick=()=>loaders[state.page]?.();$('#modalClose').onclick=closeModal;$('#modalBackdrop').addEventListener('click',e=>{if(e.target===$('#modalBackdrop'))closeModal()});
$$('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#userSearchBtn').onclick=loadUsers;$('#reloadSubscriptions').onclick=loadSubscriptions;$('#reloadPayments').onclick=loadPayments;$('#createLicenseBtn').onclick=openCreateLicense;$('#deviceSearchBtn').onclick=loadDevices;$('#auditSearchBtn').onclick=loadAudit;
window.openUser=openUser;window.setUserStatus=setUserStatus;window.grantPlan=grantPlan;window.resetUsage=resetUsage;window.createLicense=createLicense;window.setLicense=setLicense;window.setDevice=setDevice;window.savePlan=savePlan;window.toast=toast;
bootstrap();
